### ISSUE TITLE
[Bug]: Memory Leak / No way to kill running captcha instances

### ISSUE THREAD

**Issue by Quetlo** [fabianwennink/IconCaptcha-PHP#46]
### Bug report requirements

- [X] I have confirmed that this is a bug and not a configuration/user error.
- [X] I have searched for existing issues and confirmed that my issue has not been reported before.

### IconCaptcha version

4.0.3

### PHP version

8.0

### Browsers affected

Google Chrome

### Expectation

When captcha is completed or deleted, it should not continue to send request regularly.

### Actual behaviour

If the option DisplayInitialMessage is set to false,
Although the captcha is completed or deleted, it continues to send requests regularly in background.
After one captcha it's no big deal, but after completing multiple captchas, it starts to send as many regular requests so it quickly becomes a problem...

Please, just add a way to remove a captcha so this behaviour stops.

**Comment by fabianwennink** [comment]
Hi @Quetlo! Could you please elaborate your issue, perhaps with a screen recording? In my environment, the captcha does not make requests on its own once a captcha has been completed - even when setting the `displayInitialMessage` option to `false`. 

The only case the captcha makes requests on its own is if no data could be loaded from the server, e.g. when receiving a 4xx or 5xx status code. It will retry to fetch a challenge if it encounters an error. There is no limit on how many times it can retry, which might be something I could implement to prevent server spamming in this particular case. However, retrying on a 5xx status indicates something is incorrectly setup on your IconCaptcha backend which should be addressed.

**Comment by fabianwennink** [comment]
Hi @Quetlo! You can ignore my previous notification, as I now see what you mean. The issue seems to be related to the 'invalidation' feature, which automatically invalidates a captcha after a certain time. Somehow, this invalidation process still takes place even after completing a captcha - which obviously shouldn't happen. I'll look into it and release a fix later!

**Comment by fabianwennink** [comment]
Hi again. In my previous comment, I forgot about the 'completion invalidation' feature in the PHP config (see [here](https://github.com/fabianwennink/IconCaptcha-PHP/wiki/Configuration#validationcompletionexpiration)). The behavior you mention in your issue, although maybe a bit strange combined with `displayInitialMessage`, is expected behavior and not a bug. 

By setting the value of the PHP 'completion invalidation' option to anything other than `0`, the captcha widget will automatically invalidate any completed challenge after the set amount of time - both in the client and on the server (a request).

Because the `displayInitialMessage` option is set to `false`, the client will immediately request a new challenge from the server after the completed one was invalidated. Assuming you deleted the widget from the screen (by deleting the DOM), this will **not** stop the JavaScript from running its cycle of invalidating and requesting a new challenge, and you end up with infinite periodic requests in the background without seeing the widget itself reset.

```
challenge loaded -> completed -> invalidated (completion expired) -> challenge loaded -> invalidated (inactivity) -> challenge loaded -> etc...
```

My advise is to not delete the widget at all as the scripts are not intended to work this way. Deleting the DOM might even break the submission of the form due to it containing hidden input fields which are now missing. You may also want to disable the invalidation options in the PHP config, as they kind of clash with the `displayInitialMessage` option. This way it wont request a new challenge after X time of inactivity.

If my assumption is incorrect, please let me know.
